### ISSUE TITLE
create_signal fails if name is 2 characters or less

### ISSUE THREAD

**Issue by rob-yerc** [amphoradata/python-sdk#18]
Using the python SDK (0.9.9) I'm trying to create a signal with the name of 'pH' for our water quality sites.  The create_signal fails with the following error:

  File "/home/rlrobert/epiic/fa01/.venv/lib64/python3.7/site-packages/amphora/amphora.py", line 152, in create_signal
    attributes=attributes)
  File "/home/rlrobert/epiic/fa01/.venv/lib64/python3.7/site-packages/amphora_api_client/models/signal.py", line 64, in __init__
    self._property = _property
  File "/home/rlrobert/epiic/fa01/.venv/lib64/python3.7/site-packages/amphora_api_client/models/signal.py", line 111, in _property
    r"Invalid value for `_property`, must be a follow pattern or equal to `/^[a-z][a-zA-Z_]{2,20}$/`"
ValueError: Invalid value for `_property`, must be a follow pattern or equal to `/^[a-z][a-zA-Z_]{2,20}$/`

**Comment by xtellurian** [comment]
@rob-yerc we've reserved property names less than 3 characters for system use. For example, 't' is the property name for timestamp, and 'wt' is the property name for write time.

The error you're seeing is a regex validation failure because the property name is too short.

The regex is `/^[a-z][a-zA-Z_]{2,20}$/` you can use a [regex tool](https://regexr.com/545iu) to test the name before trying to create the signal

My suggestion is to change the property name - perhaps you can use a property name of "acidity" with [units](https://docs.amphoradata.com/docs/guides/python/python-upload-signal#define-signals-on-your-amphora) "pH"

**Comment by xtellurian** [comment]
Closing this as the behaviour is intentional
